package ams;

import java.awt.*;
import javax.swing.*;
import java.sql.*;

public class ForgotPassword extends javax.swing.JFrame {

    /**
     * Creates new form UpadationForm
     */
    Connection con;
    PreparedStatement pst;
    ResultSet rs;

    public ForgotPassword() {
        initComponents();
        initialize();
        con = JavaDatabase.ConnectToDB();
    }

    private void initialize() {
        setTitle("Forgot Password");
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setSize(900, 600);
        setVisible(true);
    }

    public void Search() {
        String a1 = tfUsername.getText();

        String sql = "SELECT * FROM user_login WHERE Username = '" + a1 + "'";
        try {
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();

            if (rs.next()) {
                tfName.setText(rs.getString(2));
                tfYourSecurityQuestion.setText(rs.getString(3));

            } else {
                JOptionPane.showMessageDialog(null, "Incorrect Username!");
            }
            pst.close();
            rs.close();
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    public void Retrieve() {
        String a2 = tfAnswer.getText();
        String sql = "SELECT * FROM user_login WHERE Answer = '" + a2 + "'";
        try {
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();

            if (rs.next()) {
                tfYourPassword.setText(rs.getString(5));
            }
            pst.close();
            rs.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbLogin = new javax.swing.JLabel();
        lbYourPassword = new javax.swing.JLabel();
        lbAnswer = new javax.swing.JLabel();
        lbYourSecurityQuestion = new javax.swing.JLabel();
        lbName = new javax.swing.JLabel();
        lbUsername4 = new javax.swing.JLabel();
        tfYourPassword = new javax.swing.JTextField();
        tfAnswer = new javax.swing.JTextField();
        tfYourSecurityQuestion = new javax.swing.JTextField();
        tfUsername = new javax.swing.JTextField();
        tfName = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnRetrieve = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbLogin.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lbLogin.setText("FORGOT PASSWORD");
        jPanel1.add(lbLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 90));

        lbYourPassword.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbYourPassword.setText("Your Password");
        getContentPane().add(lbYourPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, -1, -1));

        lbAnswer.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbAnswer.setText("Answer");
        getContentPane().add(lbAnswer, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, -1, -1));

        lbYourSecurityQuestion.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbYourSecurityQuestion.setText("Your Security Question");
        getContentPane().add(lbYourSecurityQuestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, -1, -1));

        lbName.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbName.setText("Name");
        getContentPane().add(lbName, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, -1));

        lbUsername4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbUsername4.setText("Username");
        getContentPane().add(lbUsername4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        tfYourPassword.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tfYourPassword.setToolTipText("");
        tfYourPassword.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        tfYourPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfYourPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(tfYourPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 410, 450, 40));

        tfAnswer.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tfAnswer.setToolTipText("");
        tfAnswer.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        tfAnswer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAnswerActionPerformed(evt);
            }
        });
        getContentPane().add(tfAnswer, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 340, 450, 40));

        tfYourSecurityQuestion.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tfYourSecurityQuestion.setToolTipText("");
        tfYourSecurityQuestion.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        tfYourSecurityQuestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfYourSecurityQuestionActionPerformed(evt);
            }
        });
        getContentPane().add(tfYourSecurityQuestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 270, 450, 40));

        tfUsername.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tfUsername.setToolTipText("");
        tfUsername.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        tfUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUsernameActionPerformed(evt);
            }
        });
        tfUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfUsernameKeyReleased(evt);
            }
        });
        getContentPane().add(tfUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 450, 40));

        tfName.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tfName.setToolTipText("");
        tfName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        tfName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNameActionPerformed(evt);
            }
        });
        getContentPane().add(tfName, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, 450, 40));

        btnSearch.setBackground(new java.awt.Color(0, 255, 255));
        btnSearch.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setText("SEARCH");
        btnSearch.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 500, 220, 40));

        btnBack.setBackground(new java.awt.Color(0, 255, 0));
        btnBack.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("BACK");
        btnBack.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 500, 220, 40));

        btnRetrieve.setBackground(new java.awt.Color(255, 102, 0));
        btnRetrieve.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnRetrieve.setForeground(new java.awt.Color(255, 255, 255));
        btnRetrieve.setText("RETRIEVE");
        btnRetrieve.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRetrieve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetrieveActionPerformed(evt);
            }
        });
        getContentPane().add(btnRetrieve, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 500, 220, 40));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfYourPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfYourPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfYourPasswordActionPerformed

    private void tfAnswerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAnswerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAnswerActionPerformed

    private void tfYourSecurityQuestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfYourSecurityQuestionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfYourSecurityQuestionActionPerformed

    private void tfUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUsernameActionPerformed

    private void tfNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNameActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        Search();
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        dispose();
        Login login = new Login();
        login.show();
    }//GEN-LAST:event_btnBackActionPerformed

    private void tfUsernameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfUsernameKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_tfUsernameKeyReleased

    private void btnRetrieveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetrieveActionPerformed
        // TODO add your handling code here:
        Retrieve();
    }//GEN-LAST:event_btnRetrieveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ForgotPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRetrieve;
    private javax.swing.JButton btnSearch;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbAnswer;
    private javax.swing.JLabel lbLogin;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbUsername4;
    private javax.swing.JLabel lbYourPassword;
    private javax.swing.JLabel lbYourSecurityQuestion;
    private javax.swing.JTextField tfAnswer;
    private javax.swing.JTextField tfName;
    private javax.swing.JTextField tfUsername;
    private javax.swing.JTextField tfYourPassword;
    private javax.swing.JTextField tfYourSecurityQuestion;
    // End of variables declaration//GEN-END:variables
}
