package ams;

import java.awt.*;
import java.sql.*;
import javax.swing.*;

public class Signup extends javax.swing.JFrame {

    /**
     * Creates new form Signup
     */
    Connection con;
    PreparedStatement pst;

    public Signup() {
        initComponents();
        initialize();
        con = JavaDatabase.ConnectToDB();
    }

    public final void initialize() {
        setTitle("Signup");
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setSize(900, 600);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbLogin = new javax.swing.JLabel();
        lbYourPassword = new javax.swing.JLabel();
        lbAnswer = new javax.swing.JLabel();
        lbYourSecurityQuestion = new javax.swing.JLabel();
        lbName = new javax.swing.JLabel();
        lbUsername4 = new javax.swing.JLabel();
        tfYourPassword = new javax.swing.JTextField();
        tfAnswer = new javax.swing.JTextField();
        tfUsername = new javax.swing.JTextField();
        tfName = new javax.swing.JTextField();
        btnCreate = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        cbYourSecurityQuestion = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbLogin.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lbLogin.setText("SIGNUP");
        jPanel1.add(lbLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 80));

        lbYourPassword.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbYourPassword.setText("Your Password");
        getContentPane().add(lbYourPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, -1, -1));

        lbAnswer.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbAnswer.setText("Answer");
        getContentPane().add(lbAnswer, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, -1, -1));

        lbYourSecurityQuestion.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbYourSecurityQuestion.setText("Your Security Question");
        getContentPane().add(lbYourSecurityQuestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, -1, -1));

        lbName.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbName.setText("Name");
        getContentPane().add(lbName, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        lbUsername4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbUsername4.setText("Username");
        getContentPane().add(lbUsername4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1));

        tfYourPassword.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tfYourPassword.setToolTipText("");
        tfYourPassword.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        tfYourPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfYourPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(tfYourPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 400, 450, 40));

        tfAnswer.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tfAnswer.setToolTipText("");
        tfAnswer.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        tfAnswer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAnswerActionPerformed(evt);
            }
        });
        getContentPane().add(tfAnswer, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, 450, 40));

        tfUsername.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tfUsername.setToolTipText("");
        tfUsername.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        tfUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUsernameActionPerformed(evt);
            }
        });
        getContentPane().add(tfUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, 450, 40));

        tfName.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tfName.setToolTipText("");
        tfName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        tfName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNameActionPerformed(evt);
            }
        });
        getContentPane().add(tfName, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, 450, 40));

        btnCreate.setBackground(new java.awt.Color(255, 102, 0));
        btnCreate.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnCreate.setForeground(new java.awt.Color(255, 255, 255));
        btnCreate.setText("CREATE");
        btnCreate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        getContentPane().add(btnCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 490, 360, 40));

        btnBack.setBackground(new java.awt.Color(0, 255, 0));
        btnBack.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("BACK");
        btnBack.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 490, 360, 40));

        cbYourSecurityQuestion.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        cbYourSecurityQuestion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "What is your mother's name?", "What is your nick name?", "Who is your first childhood friend?", "What is your first school name?" }));
        cbYourSecurityQuestion.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        getContentPane().add(cbYourSecurityQuestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, 450, 40));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfYourPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfYourPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfYourPasswordActionPerformed

    private void tfAnswerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAnswerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAnswerActionPerformed

    private void tfUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUsernameActionPerformed

    private void tfNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNameActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "INSERT INTO user_login (Username,Name,Password,Sec_Q,Answer) VALUES(?,?,?,?,?)";
            pst = con.prepareStatement(sql);
            pst.setString(1, tfUsername.getText());
            pst.setString(2, tfName.getText());
            pst.setString(3, tfYourPassword.getText());
            pst.setString(4, (String) cbYourSecurityQuestion.getSelectedItem());
            pst.setString(5, tfAnswer.getText());
            pst.execute();
            JOptionPane.showMessageDialog(null, "Created New Account!");
            tfUsername.setText("");
            tfName.setText("");
            cbYourSecurityQuestion.setSelectedItem(-1);
            tfAnswer.setText("");
            tfYourPassword.setText("");
            tfUsername.requestFocus();

        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        dispose();
        Login login = new Login();
        login.show();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreate;
    private javax.swing.JComboBox<String> cbYourSecurityQuestion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbAnswer;
    private javax.swing.JLabel lbLogin;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbUsername4;
    private javax.swing.JLabel lbYourPassword;
    private javax.swing.JLabel lbYourSecurityQuestion;
    private javax.swing.JTextField tfAnswer;
    private javax.swing.JTextField tfName;
    private javax.swing.JTextField tfUsername;
    private javax.swing.JTextField tfYourPassword;
    // End of variables declaration//GEN-END:variables
}
